// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// HyperLAU
List HyperLAU(NumericMatrix obs, Nullable<NumericMatrix> initialstates, NumericVector nboot, NumericVector model, NumericVector rate);
RcppExport SEXP _hyperlau_HyperLAU(SEXP obsSEXP, SEXP initialstatesSEXP, SEXP nbootSEXP, SEXP modelSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type initialstates(initialstatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(HyperLAU(obs, initialstates, nboot, model, rate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hyperlau_HyperLAU", (DL_FUNC) &_hyperlau_HyperLAU, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hyperlau(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
