// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// HyperLAU
List HyperLAU(NumericMatrix obs, Nullable<NumericMatrix> Xinitialstates, NumericVector Xbootstrap, NumericVector Xmodel, NumericVector Xrate, NumericVector Xnboot);
RcppExport SEXP _hyperlau_HyperLAU(SEXP obsSEXP, SEXP XinitialstatesSEXP, SEXP XbootstrapSEXP, SEXP XmodelSEXP, SEXP XrateSEXP, SEXP XnbootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type Xinitialstates(XinitialstatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xbootstrap(XbootstrapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xmodel(XmodelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xrate(XrateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xnboot(XnbootSEXP);
    rcpp_result_gen = Rcpp::wrap(HyperLAU(obs, Xinitialstates, Xbootstrap, Xmodel, Xrate, Xnboot));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hyperlau_HyperLAU", (DL_FUNC) &_hyperlau_HyperLAU, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_hyperlau(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
