# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' HyperLAU computation (Armadillo)
#'
#' @param obs Numeric matrix of observations
#' @param Xinitialstates optional
#' @param Xbootstrap optional
#' @param Xmodel optional
#' @param Xrate optional
#' @param Xnboot optional
#' 
#' @return A fitted HyperLAU model, including a dataframe of transitions, vector of likelihoods, and the dimensionality of the problem
#' @examples
#' data = matrix(c(0,0,1, 0,1,1, 1,1,1), ncol=3, nrow=3)
#' fit = HyperLAU(data)
#' @export
HyperLAU <- function(obs, Xinitialstates = NULL, Xbootstrap = 0L, Xmodel = -1L, Xrate = 1.001, Xnboot = 1L) {
    .Call(`_hyperlau_HyperLAU`, obs, Xinitialstates, Xbootstrap, Xmodel, Xrate, Xnboot)
}

