# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' HyperLAU computation (Armadillo)
#'
#' @param obs Numeric matrix of observations
#' @param initialstates optional
#' @param model optional
#' @param rate optional
#' @param nboot optional
#' 
#' @return A fitted HyperLAU model, including a dataframe of transitions, vector of likelihoods, and the dimensionality of the problem
#' @examples
#' data = matrix(c(0,0,1, 0,1,1, 1,1,1), ncol=3, nrow=3)
#' fit = HyperLAU(data)
#' @export
HyperLAU <- function(obs, initialstates = NULL, nboot = 0L, model = -1L, rate = 1.001) {
    .Call(`_hyperlau_HyperLAU`, obs, initialstates, nboot, model, rate)
}

